### ISSUE TITLE
Not able to run angular part

### ISSUE THREAD

**Issue by ghost** [abhilashahyd/ethdapp#2]
Hey I get the below error while running the ng serve command

ERROR in src/app/app.component.ts(9,38): error TS2304: Cannot find name 'ngOnInit'.
src/app/app.component.ts(25,36): error TS2339: Property 'fromAccount' does not exist on type '{}'.
src/app/app.component.ts(26,31): error TS2339: Property 'balance' does not exist on type '{}'.
src/app/ethcontract.service.ts(34,11): error TS2304: Cannot find name 'web3'.
src/app/ethcontract.service.ts(36,61): error TS2304: Cannot find name 'web3'.
src/app/ethcontract.service.ts(63,21): error TS2304: Cannot find name 'web3'.
src/polyfills.ts(75,1): error TS2304: Cannot find name 'global'.
src/polyfills.ts(75,17): error TS2304: Cannot find name 'global'.
src/polyfills.ts(75,34): error TS2304: Cannot find name 'require'.

**Comment by abhilashahyd** [comment]
Please take the latest build and follow the readme to run the application and revert if you are still facing issues.

**Comment by Sylar111** [comment]
const Web3 = require('web3');
const web3 = new Web3();
will fix the errors in ethcontract.service.ts
Still got errors:
src/app/app.component.ts(25,36): error TS2339: Property 'fromAccount' does not exist on type '{}'.
src/app/app.component.ts(26,31): error TS2339: Property 'balance' does not exist on type '{}'.
src/polyfills.ts(75,1): error TS2304: Cannot find name 'global'.
src/polyfills.ts(75,17): error TS2304: Cannot find name 'global'.
src/polyfills.ts(75,34): error TS2304: Cannot find name 'require'.
Please fix it

**Comment by abhilashahyd** [comment]
Closing the issue as the above errors are fixed in latest build. Please reopen if issue still exists.
